name: "Backstop Review"
description: "Runs whenever detecting a PR comment and setting a failed backstop check to success."
inputs:
  github_token:
    required: true
  check_name:
    required: true
    default: "BackstopJS visual test"
outputs:
  visual:
    description: "Is it successful"
runs:
  using: "node12"
  main: "dist/index.js"
