name: 'Backstop Review'
description: 'Runs whenever detecting a PR comment and setting a failed backstop check to success.'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'