name: "Approve failure"
description: "Approve any check no matter it's actual conclusion."
inputs:
  github_token:
    required: true
  check_name:
    required: true
    default: "BackstopJS visual test"
  command:
    required: true
    default: "backstop approve"
runs:
  using: "node12"
  main: "dist/index.js"
