name: Test

# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issue_comment
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
