name: Test

on:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issue_comment
  issue_comment:
    types: [created]

jobs:
  test:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Basic Failure
          conclusion: failure

      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Basic Success
          conclusion: success

      - uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
